document.addEventListener("DOMContentLoaded", function() {
    const resultLabel = document.getElementById("result");
    const spinButotn = document.getElementById("spinButton");

    spinButton.addEventListener("click", function () {
        const selectedRestaurant = spinWheel(restaurantNames);
        resultLabel.textContent = "Result: " + selectedRestaurant;
    })

    function spinWheel(restaurantNames) {
        const randomIndex = Math.floor(Math.random() * restaurantNames.length);
        return restaurantNames[randomIndex];
    }

    const restaurantNames = [
        "坡底 金龙咖喱鱼头",
        "坡底 Triple K 牛肉麵",
        "坡底 协裕面包西果厂",
        "坡底 锦华茶餐室",
        "坡底 阿福街新山蚝煎",
        "坡底 Zenith Mall 海底捞",
        "坡底 Botak Asam Pedas 新自立餐室",
        "坡底 RSX Fish Noodle 榕树下金目鲈粿條汤",
        "坡底 上记鸭肉,牛肉麵",
        "坡底 JBCC 4 Fingers Crispy Chicken",
        "坡底 CITY SQUARE Din Tai Fung 鼎泰豐",
        "坡底 CITY SQUARE Bornga 韩国餐",
        "坡底 CITY SQUARE SEOUL GARDEN",
        "Bukit Indah 顺发肉骨茶",
        "Bukit Indah Anmour 西餐",
        "Bukit Indah Sushi Mentai",
        "Bukit Indah 丁加奴鱼麵",
        "Bukit Indah 华人煎饼 厨师小食馆",
        "Bukit Indah 大马粿条仔",
        "Bukit Indah 福生早市咖啡店/晚市煮炒",
        "Bukit Indah 63咖啡店",
        "Bukit Indah 亿家海鲜",
        "Bukit Indah 鼎盛田鸡粥",
        "Bukit Indah 大火山擂茶",
        "Bukit Indah 喜羊羊猪肉粉",
        "Bukit Indah Jeju Black Korean",
        "Bukit indah Paper Restaurant",
        "Bukit Indah 怡保状元及等粉",
        "Bukit Indah 小园林中国烧烤",
        "Bukit Indah 东南咖啡店",
        "Bukit Indah 麻辣香锅",
        "Bukit Indah BBQ Box",
        "Bukit Indah 住家 Ikan Bakar Truck车仔 烧鱼",
        "Bukit Indah 住家 Homemake Nasi Lemak",
        "Bukit Indah Zen+ Korea buffet",
        "Bukit Indah Sisters BBQ Korea",
        "Bukit Indah Sorella Cafe",
        "Bukit Indah 大侠上上签火锅",
        "Bukit Indah 阿公辣沙",
        "Bukit Indah 吉麵家",
        "Bukit Indah 七福健康素食园 (素)",
        "Bukit Indah Mr. Roti",
        "Bukit Indah 海客Kopitam",
        "Nusa Bestari 大成渌渌",
        "Nusa Bestari Lar Kopi",
        "Nusa Bestari Khunya Thai Kitchen",
        "Nusa Bestari 庆丰咖啡店",
        "Nusa Bestari 一家特式鱼头",
        "Nusa Bestari HengPark咖啡店(可爱鸡)",
        "Nusa Bestari Ramen Kingu House Japanese",
        "Nusa Bestari Changman Dim Sum 常满点心楼",
        "Nusa Bestari 王奶奶",
        "Nusa Bestari Interieur Cafe",
        "Nusa Bestari 佳佳乐苦瓜汤",
        "Nusa Bestari 鼎记牛腩粉",
        "Eco Botanic 慷美丰",
        "Eco Botanic 大成禄禄",
        "Eco Botanic Polaris Bar",
        "Eco Botanic 派克鸡扒",
        "Eco Botanic Mamu Junction",
        "Eco Botanic 四夕豆花",
        "Eco Botanic Sushi Plus",
        "Eco Botanic The Banana Leaf",
        "Kota Tinggi 强记肉骨茶",
        "Kota Tinggi 华东茶室",
        "Kota Tinggi 国花茶餐室",
        "Taman Sentosa 水手西餐厅 Pahpai Steakhouse",
        "Taman Sentosa 金都101",
        "Pelangi 雾岛酒藏 Kirishima Shuzou Japanese",
        "Pelangi Kyu Izakaya (日本餐)",
        "Pelangi Kampung Carabao 100% Authentic Thai",
        "Pelangi 树下面粉果",
        "Pelangi 三楼炒米粉",
        "Pelangi 顺利面粉果",
        "Pelangi 海皇粿条仔",
        "Pelangi 三楼Ice Kacang",
        "Pelangi 海威云吞麵",
        "Pelangi 赤鬼",
        "Pelangi 小龙行江湖",
        "Pelangi 辣庄",
        "Pelangi Kofu口福美食阁",
        "Pelangi Furusato Japanese 日本料理",
        "Pelangi Cheelicious Bakery",
        "Pelangi D'Cafe",
        "Pelangi Grill Bar Steak House",
        "Pelangi 大丰擂茶",
        "Pelangi 成蒸鱼与肉骨茶餐室",
        "Pelangi Fat Fish 肥鱼",
        "Pelangi Ikan Bakar Tampin 淡边铁板烧鱼",
        "Pelangi 食得福美食中心",
        "Pelangi 古早人",
        "Pelangi Naughty Bali Johor Bahru",
        "Sentosa 牛魔王牛肉麺",
        "大马 万香生肉面",
        "龙园 阿明家乡小炒(三楼干米粉)",
        "Larkin 真功夫面粉糕",
        "Tampoi 兴福 肉骨茶蒸鱼",
        "Tampoi Laksa",
        "Tampoi 阿B淡杯全蛋云吞面",
        "Tampoi Nasi Kukus Gulai Kawah D’cempaka",
        "Plaza Angsana Mee Rebus",
        "Aeon Terbau 吉品合Jipinhe Scones",
        "Aeon Terbau Kinsahi Japanese",
        "Aeon Terbau Restoran Black Canyon",
        "Aeon Terbau 古文茶 Kuu By Tea Garden",
        "Aeon Terbau Arashi Shabu-Shabu",
        "Mount Austin 锅妈",
        "Mount Austin 巴九门火锅",
        "Mount Austin 肥肥蟹",
        "Mount Austin 功夫煲 Kungfu Wok 猪肚鸡",
        "Mount Austin Mizu 日式 x 结合韩式料理",
        "Mount Austin Cafe de flora 泰国餐",
        "Mount Austin 上汤啦啦,啊胜露露",
        "Mount Austin 日本餐和乐屋",
        "Mount Austin 宽窄巷子 成都串串香",
        "Mount Austin Khem Thai 泰国餐",
        "Mount Austin Hoobaa Hotpot 火爆锅",
        "Mount Austin Ramen Hitoyoshi Malaysia",
        "Mount Austin 131黄金BBQ火锅",
        "Mount Austin Capitol Seafood 古城海鲜",
        "Mount Austin JWC, The Factory 30",
        "Mount Austin 发哥撸串",
        "Mount Austin 老陈粿条汤",
        "Mount Austin 小龙坎火锅",
        "Mount Austin 新皇庭",
        "Mount Austin One two Eat Cafe",
        "Mount Austin 古来云来包点",
        "Mount Austin 阿明帝皇鸭",
        "Mount Austin 糖水妹 Food Truck",
        "Mount Austin The Bierhaus",
        "Mount Austin Sushi Zento 膳户",
        "Mount Austin The Atlas Maison",
        "Mount Austin 芳源咖啡店",
        "Mount Austin Ramen Hitoyoshi",
        "Mount Austin Top Fish House 一品鱼屋",
        "Mount Austin 简单云吞面",
        "Mount Austin 宽城子",
        "Mount Austin 佳香点心茶楼",
        "Mount Austin 大马粿条仔",
        "Mount Austin 串哥哥",
        "Mount Austin YiDingXiang 燚鼎香麻辣香锅",
        "Mount Austin Heart Garden Hotpot 心苑锅(心厨)",
        "Mount Austin 霸稻 Kopitam",
        "Taman Daya Kuroma Bufftet",
        "Taman Daya 锦成点心茶楼",
        "Taman Daya 旺角美食中心 (Ayam penyet)",
        "Taman Daya 顺发肉骨茶",
        "Setia Indah 水记鸡饭",
        "Setia Indah 亿家海鲜",
        "Setia Indah 阿彬养生肉骨茶",
        "Setia Indah 星北京鸡饭",
        "Setia Indah 喜来轩煮炒",
        "Eco Palladium Amazone Buffet",
        "Eco Palladium 糖朝",
        "Eco Palladium 蜜雪冰城",
        "Eco Palladium 南洋茶室",
        "Eco Palladium 新国泰酒楼",
        "Eco Palladium The Brew House",
        "Eco Palladium The Bierhaus",
        "Eco Palladium B CAFE by JVL Concept",
        "Paradigm mall 有间面馆",
        "Stulang 汶强粿条仔",
        "Stulang 烧鱼",
        "Sutera Charcoal Cafe",
        "Sutera 牛魔日式烧烤 Yakiniku",
        "Sutera 二重丸",
        "Sutera 上井寿司 Kamii Sushi",
        "Sutera 食客韩国餐",
        "Sutera 蜀大侠火锅",
        "Sutera Maco Cafe",
        "Sutera 华美 Kopitiam",
        "Sutera 壹禾豐•人文茶館",
        "Sutera Palsaik 八色烤肉",
        "Sutera Dong Seoul",
        "Sutera Hock Kee Kopitiam",
        "Sutera 狮城芽笼九巷田鸡粥",
        "Sutera 宽窄巷子",
        "Sutera MeJa Cafe",
        "Sutera The Bierhaus",
        "Sutera 谁鱼争锋",
        "Sutera 思源香港点心",
        "Sutera Uncle Don",
        "Sutera 蒸老二米粉",
        "Sutera Warakuya Japanese Garden",
        "Sutera 北京楼",
        "Sutera 阿水榴莲专卖店",
        "Sutera 发哥澛串 - 冷锅串串香",
        "Sutera Ah Hong Kopitiam",
        "Sutera Verbena Cake",
        "Sutera Wa Zen Izakaya Japanese",
        "Sutera GC Cafe",
        "Sutera 潮火锅",
        "Sutera YOU by JWC Cafe",
        "Sutera 心厨心麵馆",
        "Sutera 三羊澳门秘制羊腩煲",
        "Sutera 赞麺館猪肉粉 Like Mee Noodle House",
        "Sutera Signature by Nosh (可带宠物)",
        "Pandan 班兰牛肉面",
        "Pandan Mutton Soup 羊肉麵",
        "Gelang Patah 天来螃蟹",
        "Gelang Patah 蔡记煮炒",
        "Gelang Patah 惠海咖啡店",
        "Gelang Patah 啊华牛肉面, (羊肉汤)",
        "Kulai Nasi Lemak wak kentut",
        "Kulai 莫搞牛肉猪肉海鲜",
        "Kulai 世华肉骨茶",
        "Kulai 古来豆花",
        "Kulai 云来点心楼",
        "Kulai 回味生肉粉",
        "Kulai 客家小食馆",
        "Kulai 顺记苦瓜汤",
        "Kulai Lemon Tree",
        "Senai 金华茶餐室糕点",
        "Skudai 士古来新海珍鸭肉",
        "Skudai 士古来 晶晶云吞麵",
        "Skudai 皇后 来记西刀鱼丸",
        "Skudai 皇后 华仔炸年糕三合一",
        "Skudai 皇后 炭烧福建面",
        "Skudai 皇后 水记海南鸡饭。炖汤",
        "Skudai 皇后 成记鸡饭",
        "Skudai 皇后 民糕点",
        "Skudai 皇后 刘记粿条仔",
        "Skudai 皇后 TJ Food Centre 东嘉美食阁,鸭饭",
        "Skudai 皇后 嘉宾mamak档",
        "Skudai 皇后 兴兴卤伊面",
        "Skudai 皇后 阿财砂煲肉骨茶",
        "Skudai 皇后 777咖啡店",
        "Skudai 皇后 安记酿豆腐",
        "Skudai 皇后 新北京起骨海南鸡饭",
        "Skudai 皇后 Super Big Don House 大爆丼",
        "Skudai 鼎轩 Din Sean Kopitiam",
        "Skudai 明记金宝手工猪肠粉",
        "Skudai 八哩半的大家发鸭肉",
        "Skudai 嘉宾隔壁 Nasi Lemak",
        "Skudai La Pasta",
        "Skudai 发财小炒",
        "Skudai Sinsonson 新诵诵 云吞麵",
        "Skudai Restoran Tong 東肉骨茶(瓦煲)",
        "Impian Emas 杨家美食 虾面",
        "Impian Emas 有记XO烧腊之家",
        "Impian Emas 鸿胜美食阁",
        "Impian Emas Restaurant OMJ",
        "Impian Emas 63 咖喱鱼头海鲜餐室",
        "Impian Emas 南方养生馆(素食)",
        "Impian Emas 金山楼 云吞麵",
        "Mutiara Rini Genesis Steamboat 创世纪火锅",
        "Mutiara Rini 南发兴咖啡店",
        "Mutiara Rini 118 Mookata House",
        "Mutiara Rini 皇朝鱼炉大王",
        "Perling 珍珠坊 - 家乡瓦煲小酌",
        "Perling 大四喜香港点心楼",
        "Perling Nasi lemak Mana Lagi",
        "Perling 德记鸡饭",
        "Perling 华胜美食中心,好味猪杂汤",
        "Perling 大四喜美食阁 炒粿条",
        "Perling 伍佰美食馆 何明记云吞面",
        "Perling 北海仔虾面",
        "Perling LC Half Kopitiam 牛肉麵",
        "Perling Petronal隔壁 Nasi Ayam Penyet",
        "Perling Ikan Bakar Perling",
        "Johor Jaya 肥龙 炸鱼米粉",
        "Johor Jaya Open Food Court夜市美食街",
        "Johor Jaya 祥华人煎饼",
        "Johor Jaya 土司坊",
        "Johor Jaya 一碗功夫牛肉麵",
        "Johor Jaya Let’s Eat为食坊",
        "Johor Jaya 角头间肉骨茶无骨唐鯊",
        "Johor Jaya 印尼炒饭",
        "Johor Jaya 老店肉骨茶",
        "Johor Jaya 华阳 Oriental Kopi",
        "Johor Jaya Kim Cafe Kopitiam",
        "Johor Jaya 德莱鱼肉米粉",
        "Johor Jaya 新加东肉粽",
        "Bakawali 祖传粿条仔",
        "Bakawali 发亮鸡饭 - 肉骨茶",
        "Senibong 浅水湾海番村",
        "Senibong Cave 醉码头火锅",
        "Molek Kopilicious",
        "Molek Nasi Kandar Hijrah",
        "Molek 碳马 Tanba",
        "Molek Auntie Lim Kopitiam",
        "Molek 好一家火锅",
        "Molek 7 Pavilion Fruits 果佳鲜果",
        "Molek Heritage Signature",
        "Ulu Tiram 新东升咖啡店",
        "Ulu Tiram 卫生圆茶室",
        "Taman Gaya 余小二,小龙虾",
        "Taman Gaya 食家庄美食坊",
        "Permas 十五楼阿坚粿条汤",
        "Permas 霸王鸭饭",
        "Permas Old Street 美食坊",
        "Permas 锦旺云吞面",
        "Permas 芳源咖啡店",
        "Permas 大上海点心",
        "Permas 友记Laksa",
        "Permas King Kong Steamboat & BBQ Buffet",
        "Permas Minkan Yakiniku 平民烧烤",
        "Permas 自己人美食馆 - 1888 foodcourt 螃蟹脚",
        "Permas 家乐福火锅店",
        "Caffefour BBQ Steamboat"
    ];
})